//@version=2
study("TD(9+13) Reversal Overlay Indicator", shorttitle="TD(9+13) Reversal Overlay Indicator", overlay=true)
//strategy("TD Sequential 13 Alerts + Strategy Overlay", shorttitle="TD(9+13) Reversal Overlay Indicator", overlay=true,max_bars_back=500,default_qty_value=100,initial_capital=100,currency=currency.USD)

// With thanks to the scripts by glaz, bioharz and stripykitteh
// But mostly this page, which explains it beautifully: https://tradetrekker.wordpress.com/tdsequential/
// I give credit to scarf for upgrading the original version - SteveLeo

//show_sigs = input(title="Only 9s & 13s", type=bool, defval=true)

Count = close>close[4]?1:0

Count1 = Count==1 ? nz(Count1[1])==0 ? 1 : Count1[1]==1 ?2:Count1[1]==2?3:Count1[1]==3?4:Count1[1]==4?5:Count1[1]==5?6:Count1[1]==6?7:Count1[1]==7?8:Count1[1]==8?9:0:0

Counta=close<close[4]?1:0
Count2=Counta==1?nz(Count2[1])==0?1:Count2[1]==1?2:Count2[1]==2?3:Count2[1]==3?4:Count2[1]==4?5:Count2[1]==5?6:Count2[1]==6?7:Count2[1]==7?8:Count2[1]==8?9:0:0

piepb=Count1==9 and piepb[1]==0?1:piepb[1]>0?piep2[1]==13?0:nz(piepb[1])+1:0
piep2=piepb>0 and close>high[2] and close>high[1]?piep2[1]==13?0:nz(piep2[1])+1:piep2[1]==13?0:piep2[1]

piepa=Count2==9 and piepa[1]==0?1:piepa[1]>0?piep[1]==13?0:nz(piepa[1])+1:0
piep=piepa>0 and close<low[2] and close<low[1]?piep[1]==13?0:nz(piep[1])+1:piep[1]==13?0:piep[1]

col_green = color(maroon, 0)
col_red = color(green, 0)
// quick fox

//plotchar(Count1==1 and not show_sigs,char='1', color=col_green)
//plotchar(Count1==2 and not show_sigs,char='2', color=col_green)
//plotchar(Count1==3 and not show_sigs,char='3', color=col_green)
//plotchar(Count1==4 and not show_sigs,char='4', color=col_green)
//plotchar(Count1==5 and not show_sigs,char='5', color=col_green)
//plotchar(Count1==6 and not show_sigs,char='6', color=col_green)
//plotchar(Count1==7 and not show_sigs,char='7', color=col_green)
//plotchar(Count1==8 and not show_sigs,char='8', color=col_green)
//plotchar(Count1==9,char='9', color=col_green)

//renable this if you want td9
plotshape(Count1==9, "9 Bearish", text='9\n▼', style=shape.labeldown, location=location.abovebar, color=blue, textcolor=white, offset=0)

//plotchar(Count2==1 and not show_sigs,char='1', color=col_red)
//plotchar(Count2==2 and not show_sigs,char='2', color=col_red)
//plotchar(Count2==3 and not show_sigs,char='3', color=col_red)
//plotchar(Count2==4 and not show_sigs,char='4', color=col_red)
//plotchar(Count2==5 and not show_sigs,char='5', color=col_red)
//plotchar(Count2==6 and not show_sigs,char='6', color=col_red)
//plotchar(Count2==7 and not show_sigs,char='7', color=col_red)
//plotchar(Count2==8 and not show_sigs,char='8', color=col_red)
//plotchar(Count2==9,char='9', color=col_red)

//renable this if you want td9
plotshape(Count2==9, "9 Bullish", text='▲\n9', style=shape.labelup, location=location.belowbar, color=purple, textcolor=white, offset=0)


//plotshape(piep==1 and piep[1]==0?1 and not show_sigs: na, text='1', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==2 and piep[1]==1?1 and not show_sigs: na, text='2', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==3 and piep[1]==2?1 and not show_sigs: na, text='3', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==4 and piep[1]==3?1 and not show_sigs: na, text='4', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==5 and piep[1]==4?1 and not show_sigs: na, text='5', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==6 and piep[1]==5?1 and not show_sigs: na, text='6', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==7 and piep[1]==6?1 and not show_sigs: na, text='7', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==8 and piep[1]==7?1 and not show_sigs: na, text='8', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==9 and piep[1]==8?1 and not show_sigs: na, text='9', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==10 and piep[1]==9?1 and not show_sigs: na, text='10', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==11 and piep[1]==10?1 and not show_sigs: na, text='11', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==12 and piep[1]==11?1 and not show_sigs: na, text='12', location=location.belowbar, style=shape.triangledown, color=col_red)
//plotshape(piep==13 and piep[1]==12?1: na, text='13', location=location.belowbar, style=shape.triangledown, color=col_red)
plotshape(piep==13 and piep[1]==12?1: na, "13 Bullish", text='▲\n13', style=shape.labelup, location=location.belowbar, color=col_red, textcolor=white, offset=0)

// when you want to plot same two items plotshape(piep==13 and piep[1]==12?low*0.85: na, text='13', location=location.absolute, style=shape.triangledown, color=lime)
//plotshape(piep2==1 and piep2[1]==0?1 and not show_sigs: na, text='1', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==2 and piep2[1]==1?1 and not show_sigs: na, text='2', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==3 and piep2[1]==2?1 and not show_sigs: na, text='3', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==4 and piep2[1]==3?1 and not show_sigs: na, text='4', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==5 and piep2[1]==4?1 and not show_sigs: na, text='5', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==6 and piep2[1]==5?1 and not show_sigs: na, text='6', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==7 and piep2[1]==6?1 and not show_sigs: na, text='7', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==8 and piep2[1]==7?1 and not show_sigs: na, text='8', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==9 and piep2[1]==8?1 and not show_sigs: na, text='9', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==10 and piep2[1]==9?1 and not show_sigs: na, text='10', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==11 and piep2[1]==10?1 and not show_sigs: na, text='11', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==12 and piep2[1]==11?1 and not show_sigs: na, text='12', location=location.belowbar, style=shape.triangleup, color=col_green)
//plotshape(piep2==13 and piep2[1]==12?1: na, text='13', location=location.belowbar, style=shape.triangleup, color=col_green)
plotshape(piep2==13 and piep2[1]==12?1: na, "13 Bearish", text='13\n▼', style=shape.labeldown, location=location.abovebar, color=col_green, textcolor=white, offset=0)


alertcondition(Count2==9, title='TD: Buy 9', message='TD Buy 9: ')
alertcondition(Count1==9, title='TD: Sell 9', message='TD Sell 9: ')
alertcondition(piep==13 and piep[1]==12, title='TD: Buy 13', message='TD Buy 13: ')
alertcondition(piep2==13 and piep2[1]==12, title='TD: Sell 13', message='TD Sell 13: ')

golong = (piep==13 and piep[1]==12)
goshort = (piep2==13 and piep2[1]==12)

TP = input(100) * 10 //+ 2
SL = input(100) * 10 //- 2
TS = input(0) * 10
CQ = 100 //Represents % of position to enter or exit, 100% is good

TPP = (TP > 0) ? TP : na // Take profit percetnage
SLP = (SL > 0) ? SL : na // Stop loss percentage
TSP = (TS > 0) ? TS : na // Trailing stop percentage

//strategy.entry("Buy",strategy.long,when = golong)
//strategy.entry("Sell",strategy.short,when = goshort)

//strategy.exit("Close Long", "Buy", qty_percent=CQ, profit=TPP, loss=SLP, trail_points=TSP)
//strategy.exit("Close Short", "Sell", qty_percent=CQ, profit=TPP, loss=SLP, trail_points=TSP)
