//@version=4
study("NASDAQ")
zeroline = plot(0, color=#FFFFFF)
ma_interval = timeframe.isweekly ? 10 : 50
period = timeframe.isweekly ? "W" : "D"
nasd50 = sma(security("USI:ADDQ", period, close), ma_interval)
nasd50PlotValue = (dayofweek == dayofweek.monday) ? nasd50 : 
 (dayofweek == dayofweek.tuesday) ? nasd50 :
 (dayofweek == dayofweek.wednesday) ? nasd50 :
 (dayofweek == dayofweek.thursday) ? nasd50 :
 (dayofweek == dayofweek.friday) ? nasd50 : na
plotColor = (nasd50PlotValue > 0) ? #008447 : #ef242e
nasd50curve = plot(series=nasd50PlotValue, title="NASDAQ50A/D", style=2, linewidth=2, color=#FFFFFF)
fill(nasd50curve, zeroline, plotColor, transp=50)
nasd_new_high = security("USI:YRHI.NQ", "D", close)
nasd_new_low = security("USI:YRLO.NQ", "D", close)
nasdPlotValue = (dayofweek == dayofweek.monday) ? nasd_new_high-nasd_new_low : 
 (dayofweek == dayofweek.tuesday) ? nasd_new_high-nasd_new_low :
 (dayofweek == dayofweek.wednesday) ? nasd_new_high-nasd_new_low :
 (dayofweek == dayofweek.thursday) ? nasd_new_high-nasd_new_low :
 (dayofweek == dayofweek.friday) ? nasd_new_high-nasd_new_low : na
plot(nasdPlotValue, style=5, linewidth=1, color=#fddd13)

